FROM public.ecr.aws/lts/ubuntu:18.04
# FROM public.ecr.aws/docker/library/ubuntu:jammy

# Set environment variables
# Prevent Python from writing .pyc files
ENV PYTHONDONTWRITEBYTECODE=1
# Ensure stdout and stderr are flushed immediately
ENV PYTHONUNBUFFERED=1        

# Set the working directory in the container
WORKDIR /app

# Install system dependencies
RUN apt update && apt-get install -y \
    python3 \
    python3-dev \
    python3-pip \
    build-essential \
    && apt-get clean

# Install Python dependencies
COPY requirements.txt /app/

RUN pip3 install --upgrade pip  && pip install -r requirements.txt

# Copy the Django project files into the container
COPY . /app/

# Expose the port the app runs on
EXPOSE 8000

# Run the Django development server
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]